// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbszrrvfisyopmrcopga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ic3pycnZmaXN5b3BtcmNvcGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjYxNzcsImV4cCI6MjA2MzcwMjE3N30.W_QZ4Y9OHqPMndDTvLKR9kP4aqKXbcdvE3_kP51S3HU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);